### PR TITLE
Report errors

### PR DESCRIPTION
**Pull request by nadine-piveteau**
Interim solution to report validation errors by using the concept of [JsonPointers](https://tools.ietf.org/html/rfc6901).

However, this solution returns cascading error messages as the json schema has a nested structure. I'm struggeling to extract in a standardized way the initial error that causes all the others. 
 @loicgasser : Any suggestion how to approach that? 

Steps to reproduce error messages: 
1) run `node index.js`
2) send POST-request to `localhost:9010/push` that has as body `geojsons/ch.meteoschweiz.messdaten-niederschlag.json` in which you removed an arbitrary property, e.g. `"station_name" : "Arosa",`

### CODE REVIEW

**Comment by nadine-piveteau** [comment]
An exception is now thrown when the json is not valid (see generated `errorLog.log`). Because of the cascading errors the error message is huge and accordingly ugly. 
Here an example of an error message when I remove a `station_name` in one of the features in `geojsons/ch.meteoschweiz.messdaten-niederschlag.json` 
```
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/0/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /coordinates, Schema Path: #/oneOf/0/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/1/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /coordinates, Schema Path: #/oneOf/1/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/2/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /coordinates, Schema Path: #/oneOf/2/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/3/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /coordinates, Schema Path: #/oneOf/3/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/4/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /coordinates, Schema Path: #/oneOf/4/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/5/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /coordinates, Schema Path: #/oneOf/5/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/oneOf/6/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /geometries, Schema Path: #/oneOf/6/required; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/definitions/geometry/properties/type/enum; 
Error Message: should be equal to one of the allowed values, Error Path in Json: /type, Schema Path: #/properties/type/enum; 
Error Message: is a required property, Error Path in Json: /geometry, Schema Path: #/required; 
Error Message: is a required property, Error Path in Json: /properties, Schema Path: #/required; 
Error Message: is a required property, Error Path in Json: /features/2/properties/station_name, Schema Path: #/properties/properties/required; 
Error Message: should match exactly one schema in oneOf, Error Path in Json: , Schema Path: #/oneOf;
```

**Comment by nadine-piveteau** [comment]
And [here ](https://github.com/fge/sample-json-schemas/tree/master/geojson) you can find the other schema I mentioned.

**Comment by loicgasser** [comment]
Yes but only the last line is really relevant. We can propably parse it in way that it is more obvious where the problem comes from while still showing the entire error.
Maybe this lib has also more to offer when it comes to showing error logs. Did you dig into the doc?

**Comment by nadine-piveteau** [comment]
Actually, the origin of the error is caught in the penultimate error message as I removed the property `station_name` in the third feature . 
`Error Message: is a required property, Error Path in Json: /features/2/properties/station_name, Schema Path: #/properties/properties/required; `

I did some research but I haven't found yet... I'll dig deeper :)

**Pull request closed without merging**
